language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - ng lint
  # headless unit tests
  - ng test --watch=false --browsers=ChromeHeadless
  # headless e2e tests
  - xvfb-run npm run e2e
  - ng build --prod
